### PR TITLE
Recurrent Visual Attention blog post

### PR DESCRIPTION
**Pull request by nicholas-leonard**

### CODE REVIEW

**Comment by clementfarabet** [comment]
Neat!

**Comment by soumith** [comment]
this is pretty nice. I'll give the same feedback as I gave to Alban and Cedric for the Spatial Transformer networks post.

Over time, I would like the Torch blog (at least some posts) to be interesting regardless of if the audience are interested in Torch, or if they are experts in deep learning / machine learning.

Adding more visualizations, animations, etc., showing what is happening inside the network during training, and at test time over the recurrence (basically showing the attention in action) will get more general audience and have much more viewership for the post.

**Comment by nicholas-leonard** [comment]
@soumith I added some glimpse results in GIF format and some numbers. Should be ready to merge.

**Comment by nicholas-leonard** [comment]
@koraykv I added the model diagram from the paper. Hope that is alright.

**Pull request merged**
