### PR TITLE
92.45% on CIFAR blog post

### PR DESCRIPTION
**Pull request by szagoruyko**
includes some small changes to blog layout

### CODE REVIEW

**Comment by soumith** [comment]
it's live :)

**Comment by soumith** [comment]
can you tweak the CSS a little bit for the website to make it more readable.

Right now, it looks like it is much more cleaner and readable here:

https://github.com/torch/torch.github.io/blob/master/blog/_posts/2015-07-30-cifar.md

than here:

http://torch.ch/blog/2015/07/30/cifar.html

Also put the link to your code at the top of the blog post, and in bold.

**Comment by soumith** [comment]
After that we will post on various social media.

**Comment by szagoruyko** [comment]
yeah I was thinking maybe we just should embed it as a gist, it was looking much nicer.. will tweak the css

**Pull request merged**
